//LOCALHOST
###Get all contacts with a local host
GET http://localhost:3000/contacts

###Get all contacts with render
GET https://cse-341-project1-3-3bcf.onrender.com/contacts


### Get contact by id
GET https://cse-341-project1-3-3bcf.onrender.com/contacts/690fbbf9e7d614650aa290e5